glfw/glfw

- .gitignore
- examples/gears.c
- src/wgl_context.c
- src/win32_init.c
- src/win32_platform.h
- src/win32_window.c
This method uses desktop composition for efficient window transparency.
Since windows 8, composition is always on. If composition is disabled on vista or 7, transparency is simply ignored. Also, since it requires a pixel format supporting compositing, if we can't find it (e.g. windows xp) we ignore transparency similarly to how @datenwolf is doing it for glx's frame buffer configs.
This shouldn't be tested in a virtual machine.
On a side note, desktop composition can be enabled in the "Performance Options" dialog (win+r systempropertiesperformance). It is on by default but won't work unless the Aero score index has been refreshed after installing gpu drivers (Control Panel\All Control Panel Items\Performance Information and Tools).
> Add support for wgl window transparency (Vista and later)

- src/wl_window.c
This makes the examples and tests render as they do on other platforms,
with a black background instead of a transparent or semi-transparent
one.
Too bad, it made some examples look way better, but consistency is a good thing. Also waiting on #157 to provide the API to re-enable transparency.
> Always make the window surface opaque

- src/mir_window.c
https://bugs.launchpad.net/ubuntu/+source/unity8-desktop-session/+bug/1308133
Was fixed (which what bug 1477285 was!)
Remove unneeded buffer swaps for the cursor.
(Hopefully the commit message is better this time... dont really use git very often!)
> LP:1477285 Bug fixed, remove FIXME

- tests/tearing.c
The tearing test incorrectly calls itself "iconify" when printing usage information; probably just a copy-paste error.
> Correct program name printed by tearing test

- tests/gamma.c
Unlike similar test programs (e.g. tearing.c), the gamma test does not explain the meanings of the optional parameters `h` and `f`. This patch adds these explanations to the usage text.
> Add explanation of parameters to gamma test

- src/wl_init.c
This was partially inspired from #475, but some of the fixes were bogus (`free()`ing already-freed memory) and it was generally incomplete, so I preferred to restart from scratch using valgrind.
There is one remaining leak, due to the `_GLFWmonitor`s being freed before `_glfwPlatformTerminate()` is executed, making everything allocated in `_GLFWmonitorWayland` impossible to free.
> Fix a bunch of memleaks

- src/wl_init.c
- src/wl_platform.h
This commit has been copied almost verbatim from Bryce Harrington’s patch against Weston’s toytoolkit:
https://patchwork.freedesktop.org/patch/114661/
> Implement compose key for character input

- docs/Doxyfile.in
- include/GLFW/glfw3.h
This should describe all of the Wayland-specific points, mostly in
three categories:
- Missing GLFW features, for example window frame, screensaver
inhibition, clipboard or file drop.
- Missing protocols, like setting gamma on a monitor or specifying a
window icon.
- Fundamental incompatibilities with Wayland’s concepts, like trying to
handle global positioning of a window in a 2D space, trying to bring
a window to front, or trying to change the monitor’s mode.
> Add remarks to glfw3.h whenever the behaviour differs

- src/monitor.c
- src/wl_monitor.c
glfwGetMonitorName()’s documentation says “this function returns a
human-readable name”, which “typically reflects the make and model of
the monitor”.  We get these two strings in the geometry event, so we
replace the default name at this point.
> Set a proper name for outputs

- src/x11_window.c
`processEvent` in `x11_window.c` currently discards events that can not be mapped to a current GLFW window. However, this breaks clipboard functionality by failing to respond to SelectionRequest and SelectionClear events.
This commit moves processing of these important clipboard events to before the NULL window test so that they are always considered.
Fixes #961 (tentatively; there is probably an underlying structural change to be made that fixes this properly).
> Handle X11 Selection* events despite NULL window

- src/wl_init.c
This is very important, because the serial used in the Wayland button callback wasn't being updated, making functions like ```wl_shell_surface_*``` useless inside the GLFW callbacks started by the Wayland backend.
The operations for moving and resizing a window using ```wl_shell_surface_move``` and ```wl_shell_surface_resize``` expect an update serial, which is fixed by this patch.
This is related to the issues https://github.com/glfw/glfw/issues/923 and https://github.com/glfw/glfw/issues/990.
> Update serial on Wayland button callback

- src/cocoa_init.m
- src/cocoa_platform.h
- src/cocoa_window.m
When cursor isn't in normal mode and should be hidden, use `[NSCursor hide]`
method instead of setting it to blank image. This should prevent
situations when hidden cursor becomes visible after system notification
was shown.
Fixes #971
> Hide cursor instead of using blank image

- src/wl_init.c
The Wayland protocol is asynchronous, by the time we destroy a surface,
the compositor may have sent a wl_keyboard::enter or wl_pointer::enter
events which now point to no surface, yet we receive it after.
To prevent this race, we can just ignore any enter event targetting a
NULL surface.
Fixes #1150.
> Prevent a race between surface destruction and focus

- src/glx_context.c
- src/wl_init.c
- src/x11_init.c
The only functional difference is the change from `RTLD_GLOBAL` to `RTLD_LOCAL`, which is more correct in our case as we never want to expose loaded symbols to other shared objects.
> Use the _glfw_dlopen/dlsym/dlclose define

- src/wl_init.c
- src/wl_platform.h
- src/wl_window.c
This depends on #1171, and loads these two helper libraries using dlopen/dlsym/dlclose.
Only libwayland-client remains.
> Load libwayland-egl and libwayland-cursor at runtime

- .travis.yml
- CMakeLists.txt
- docs/compat.dox
- include/GLFW/glfw3.h
- src/CMakeLists.txt
- src/wl_init.c
- src/wl_platform.h
- src/wl_window.c
This protocol matches desktops much better than the deprecated wl_shell, fixing a bunch of race conditions, removing undefined behaviour, adding missing features, and generally providing a much more user-friendly experience.
Since most compositors don’t support it yet, the wl_shell_surface role is kept as fallback for now.
I haven’t tested this new code at all, since my compositor doesn’t support it yet, hence the help wanted label.
> Implement xdg-shell in addition to wl_shell

- README.md
- docs/vulkan.dox
- include/GLFW/glfw3.h
- src/vulkan.c
OpenGL / OpenGL ES cannot share presentation on a window with Vulkan.
This adds an error to `glfwCreateWindowSurface` when it is called on a
window without the GLFW_CLIENT_API hint set to GLFW_NO_API. This
prevents undefined bahevior and hard to debug crashes.
Fixes #1194.
> Vulkan: make it an error to create surface without GLFW_NO_API

- .travis.yml
The global env wasn’t global enough.
Prevents #1197 from happening again.
> Fix -Werror in Travis, env gets overriden

- src/wl_init.c
- src/wl_platform.h
- src/wl_window.c
This bumps the requested `wl_seat` version in order to get a `wl_keyboard` exposing the `repeat_info` event, adds a timerfd which we `poll()`, and then we emit a key with the `GLFW_REPEAT` action.
Fixes #1108.
> Implement key repeat on Wayland

- include/GLFW/glfw3.h
- src/CMakeLists.txt
- src/wl_init.c
- src/wl_platform.h
- src/wl_window.c
This PR implements window decorations on Wayland.
The current design is to allocate a single buffer mapped from a single pixel, and to scale it using a `wp_viewport` on each of the four surfaces.  This prevents buttons and text from being drawn there, but at least for text I’m not sure we want that inside of GLFW.
Resizing from the left, top-left or top side moves the right and bottom sides while they should stay in place, I’m not sure why, but I wouldn’t consider that a blocker either.
Disabling decorations, fullscreen, maximizing, and hidpi have all been tested now.
Here is how it looks on Weston: 
Fixes #1068.
> Implement window decorations

- CMake/modules/FindEpollShim.cmake
- CMakeLists.txt
- src/CMakeLists.txt
- src/wl_init.c
- src/wl_platform.h
re: #1219.
Mostly just ifdefs Linux joystick support to Linux. I also added linking to libepoll-shim in CMake though.
BTW, any plans for selecting between Wayland and X11 dynamically (on the fly) like the big toolkits (incl. SDL) do? [Some projects](https://github.com/kovidgoyal/kitty) are already implementing this by themselves — by building two copies of bundled glfw and dlopen'ing one of them depending on the desired backend…
> Add support for Wayland on FreeBSD and other OSes

- README.md
- docs/news.dox
- docs/window.dox
- include/GLFW/glfw3.h
- src/internal.h
- src/window.c
- tests/windows.c
Adds GLFW_FOCUS_ON_SHOW window hint and attribute for issue #1189.
This is a platform independent change which preserves behaviour for all applications written to the GLFW API. I believe I have implemented all requirements as per "Contributing a feature" guidelines.
If changes are needed I'm happy to do them. I can also clean the commit timeline if needed.
> Focus on show PR for #1189

- src/wl_init.c
- src/wl_platform.h
- src/wl_window.c
The `NULL` and frame cursors aren’t animated yet, because neither are `GLFWcursor`s, which this code depends on.
There is also no support for user animated cursors yet, since this would require changing the `glfwCreateCursor()` API.
> Add support for animated standard cursors

- src/wl_init.c
- src/wl_platform.h
- src/wl_window.c
This prevents them from looking blurry.
Note that only the NULL cursor and the ones used for decorations (resize, etc.) are rendered at scale=2 currently.  The cursors created by glfwCreateStandardCursor() and glfwCreateCursor() contain a single image which is specified to be scale=1.
In the future, GLFWcursor should be extended to support that usecase, as well as animations.
> Use HiDPI cursors on scale>1 monitors on Wayland

- CMakeLists.txt
- src/glfw_config.h.in
- src/wl_window.c
This allows the compositor to avoid having to setup and teardown a
SIGBUS signal handler whenever it needs to read from this surface, as it
knows we won’t be able to shrink the file and so doesn’t have to protect
against that.
This codepath will only be used on Linux ≥ 3.17 with glibc ≥ 2.27, and
possibly other kernels and libc.  The former code will continue to be
used as a fallback, either if memfd_create() fails or if it isn’t
available.
> Use memfd_create() and seals if available

- .travis.yml
- CMakeLists.txt
- src/CMakeLists.txt
- src/wl_init.c
- src/wl_platform.h
- src/wl_window.c
This allows compositors which prefer to draw the decorations around
clients to do so, rather than letting GLFW draw its own decorations.
The appearance is thus entirely subject to the compositor used, but
should generally be better than the current solid colour decorations we
have, which we continue to use when the compositor doesn’t support this
protocol or tells us to draw the decorations ourselves.
This new protocol has been tested against [wlroots](https://github.com/swaywm/wlroots)’s rootston compositor.
Fixes #1257.
> Add support for xdg-decoration

- src/linux_joystick.c
This potential bug was found thanks to gcc 8’s `-Wstringop-truncation` warning.
> Include the null byte in joystick path

- include/GLFW/glfw3.h
- src/wl_init.c
- src/wl_platform.h
- src/wl_window.c
Clipboard support was one of the last missing features in the Wayland backend.
The current API is not adapted to a highly asynchronous protocol such as Wayland, but fixing that will have to wait 4.0 so I did what I could. The main issue is in `glfwGetClipboardString()`, which has to dispatch the request and block until the client sending the clipboard data is done, which could potentially take a very long time. A good way to reach this state is to copy from another Wayland client, `kill -STOP` it, and paste in the GLFW program, it will then block until we `kill -CONT` the other one. A possible solution against this issue would be to set a timer and place a handler for SIGALRM, but in the general case we can expect other clients to be well-behaved.
Supersedes #358, from which one commit …
> Implement clipboard support

- src/x11_window.c
click events would have an incorrect position after changing workspace,
if the mouse didn't move in between.
(Another example where this matters is a new window, if it appears under
the cursor, clicking would lead the application to think the user clicked
at 0,0)
FWIW I've done this for kitty which has their own fork of glfw now, but I believe this applies here as well, and it's simple enough. If someone has time there probably are other small stuff like this to pick; until then I'll at least try to not make the rift too much bigger by submitting to both when applicable; unless you don't care either.
> x11 window: update cursor position on enter event

- docs/compat.dox
- include/GLFW/glfw3.h
- src/wl_init.c
- src/wl_platform.h
- src/wl_window.c
This protocol is part of the core Wayland, but it is pretty badly
designed and is missing quite a few features, and is in the process of
being phased out in compositors.  Its support in GLFW requires
duplicating pretty much every single window management codepath.
This bumps the required compositor versions to the ones which have
implemented xdg-shell, approximately two years ago, which seems sensible
to me.
> Remove wl_shell support

- src/cocoa_monitor.m
The `size` member in the `GLFWgammaramp` struct is of type `unsigned int`, so the `for` loop iterating over it should also use the type `unsigned int`.
> Use the correct type in a for loop

- src/wl_platform.h
The `name` member in the `_GLFWmonitorWayland` struct is used in two places. It is assigned the value from a variable of type `uint32_t` and is compared to another variable of type `uint32_t`, so `name` should also have the same type.
> Use the correct type for a struct member

- src/wl_window.c
When compiling with `-Wall` and `-pedantic-errors`, gcc complains with
```
warning: ISO C does not support the '%m' gnu_printf format [-Wformat=]
```
because the `%m` conversion specifier is a GNU extension.
Closes #1702.
I'm not sure if this is actually a problem for most people. This was a problem for kitty but since it has its own fork of GLFW, it isn't a big deal.
> Replace %m conversion specifier with %s and strerror()

- src/wl_init.c
This fallback is similar to the one performed in the "X11: Assume 96 DPI if RandR Monitor Size is zero" commit: https://github.com/glfw/glfw/commit/e96dc5d2199032d565b55c4177820ab28b1d67c9
Nicolas Caramelli
> Wayland: Assume 96 DPI if physical size is <= 0

- src/wl_init.c
- src/x11_init.c
- src/x11_window.c
Joystick support isn't initialized unless ``_GLFW_LINUX_JOYSTICK`` is defined, and this is never defined. I replaced the checks with checks for ``GLFW_BUILD_LINUX_JOYSTICK``, which is actually defined.
> Fix Joysticks On Linux

- src/wl_window.c
Here is a sample valgrind report for this bug:
```
% valgrind --leak-check=full build-wayland/tests/events
==163693== Memcheck, a memory error detector
==163693== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==163693== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==163693== Command: build-wayland/tests/events
==163693== 
==163693== Warning: unimplemented fcntl command: 1033
==163693== Warning: unimplemented fcntl command: 1033
Library initialized
Creating windowed mode window 1 (640x480)
==163693== Warning: unimplemented fcntl command: 1033
Main loop starting
00000000 to 1 at 2.184: Window focused
==163693== Invalid write of size 8
==163693==    at 0x1325A4: dataDeviceHandleDataOffer (wl_window.c:1678)
==163693==    by 0x4FF6FF4: ??? (in …
```
> Wayland: Fix a wrong array size for _GLFWofferWayland

- CMake/glfw3.pc.in
- src/CMakeLists.txt
If building on Windows as shared library GLFW adds the suffix "dll" to the library name. This suffix is missing in the pkg-config file.
> Fix pkg-config on Windows

- CONTRIBUTORS.md
- include/GLFW/glfw3.h
The current wording states that all keys have synthetic key release events generated after focus is lost, but keys that aren't named don't have any state held, so no such events are generated for them.
This change clarifies that only named keys have the events generated for them.
Not sure if docs changes deserve a changelog entry, if so, it can be added.
> Specify that synthetic key releases are only generated for named keys

- CONTRIBUTORS.md
- README.md
- src/wl_window.c
> Wayland: Ignore key repeat events when no window has keyboard focus

- README.md
- src/wl_window.c
Windows with keyboard focus may have an active key repeat timer. This should be reset when the window is closed, or key repeat events could be sent to a NULL window were it not for the quickfix in PR #2732.
Fixes #2741
Probably the source of #2727
> Wayland: Reset key repeat timer on window destruction
